[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"  # Updated to match OpenZeppelin requirements
optimizer = true
optimizer_runs = 200
verbosity = 2    # Show more details during testing
always_use_create_2_factory = true

[profile.default.rpc_endpoints]
bnb_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545"

[profile.default.etherscan]
bnb_testnet = { key = "${BSCSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api" }

[profile.ci]
verbosity = 3    # More verbose output for CI environments
fuzz_runs = 1000 # More fuzz runs in CI for better coverage

[profile.default.env]
PRIVATE_KEY = { value = "${PRIVATE_KEY}" }
BSCSCAN_API_KEY = { value = "${BSCSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
